### ISSUE TITLE
Building leads to errors

### ISSUE THREAD

**Issue by nikita-fuchs** [ngx-semantic/ngx-semantic#167]
Hey, thanks a 1000 times for keeping SUI alive for angular !

I'm trying to migrate from the old `ng2-semantic-ui` library, which just breaks in angular 12 for me.

After installing the two packages, I noticed two strange behaviours: 

1. ` import {SuiSegmentModule, SuiLabelModule, SuiIconModule} from "ngx-semantic";` does not work for me, I can only do 
    `import { NgxSemanticModule } from "ngx-semantic";`

2. After importing the `NgxSemanticModule` in my `app.module.ts` (and not using it anywhere else yet), I try to `ng serve` but get the following errors: 

```

./node_modules/ngx-semantic/fesm2015/ngx-semantic-modules-checkbox.mjs - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
TypeError: Cannot create property 'message' on string '/Usersxxxnode_modules/ngx-semantic/fesm2015/ngx-semantic-modules-checkbox.mjs: This application depends upon a library published using Angular version 15.0.4, which requires Angular version 14.0.0 or newer to work correctly.
Consider upgrading your application to use a more recent version of Angular.
  89 | }
  90 | SuiCheckboxComponent.ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "15.0.4", ngImport: i0, type: SuiCheckboxComponent, deps: [{ token: i0.ChangeDetectorRef }], target: i0.ɵɵFactoryTarget.Component });
> 91 | SuiCheckboxComponent.ɵcmp = i0.ɵɵngDeclareComponent({ minVersion: "14.0.0", version: "15.0.4", type: SuiCheckboxComponent, selector: "sui-checkbox", inputs: { suiType: "suiType", name: "name", suiValue: "suiValue", suiReadOnly: "suiReadOnly", disabled: "disabled", checked: "checked" }, outputs: { valueChanged: "valueChanged", checkedChange: "checkedChange" }, host: { listeners: { "click": "onClick()" }, properties: { "class": "this.classes" } }, providers: [{
     |                             ^
  92 |             provide: NG_VALUE_ACCESSOR,
  93 |             useExisting: forwardRef(() => SuiCheckboxComponent),
  94 |             multi: true'
    at run (/Usersxxxnode_modules/@babel/core/lib/transformation/index.js:27:15)
    at run.next (<anonymous>)
    at transform (/Usersxxxnode_modules/@babel/core/lib/transform.js:22:33)
    at transform.next (<anonymous>)
    at step (/Usersxxxnode_modules/gensync/index.js:261:32)
    at /Usersxxxnode_modules/gensync/index.js:273:13
    at async.call.result.err.err (/Usersxxxnode_modules/gensync/index.js:223:11)
    at /Usersxxxnode_modules/gensync/index.js:37:40

./node_modules/ngx-semantic/fesm2015/ngx-semantic-modules-dropdown.mjs - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
TypeError: Cannot create property 'message' on string '/Usersxxxnode_modules/ngx-semantic/fesm2015/ngx-semantic-modules-dropdown.mjs: This application depends upon a library published using Angular version 15.0.4, which requires Angular version 14.0.0 or newer to work correctly.
Consider upgrading your application to use a more recent version of Angular.
  14 | }
  15 | SuiDropdownMenuDividerDirective.ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "15.0.4", ngImport: i0, type: SuiDropdownMenuDividerDirective, deps: [], target: i0.ɵɵFactoryTarget.Directive });
> 16 | SuiDropdownMenuDividerDirective.ɵdir = i0.ɵɵngDeclareDirective({ minVersion: "14.0.0", version: "15.0.4", type: SuiDropdownMenuDividerDirective, selector: "[suiDropdownMenuDivider]", host: { properties: { "class": "this.classes" } }, ngImport: i0 });
     |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^m^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^m^^^^^^^^^^^^^^^^^
  17 | i0.ɵɵngDeclareClassMetadata({ minVersion: "12.0.0", version: "15.0.4", ngImport: i0, type: SuiDropdownMenuDividerDirective, decorators: [{
  18 |             type: Directive,
  19 |             args: [{'
    at run (/Usersxxxnode_modules/@babel/core/lib/transformation/index.js:27:15)
    at run.next (<anonymous>)
    at transform (/Usersxxxnode_modules/@babel/core/lib/transform.js:22:33)
    at transform.next (<anonymous>)
    at step (/Usersxxxnode_modules/gensync/index.js:261:32)
    at /Usersxxxnode_modules/gensync/index.js:273:13
    at async.call.result.err.err (/Usersxxxnode_modules/gensync/index.js:223:11)
    at /Usersxxxnode_modules/gensync/index.js:37:40

./node_modules/ngx-semantic/fesm2015/ngx-semantic-modules-sidebar.mjs - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
TypeError: Cannot create property 'message' on string '/Usersxxxnode_modules/ngx-semantic/fesm2015/ngx-semantic-modules-sidebar.mjs: This application depends upon a library published using Angular version 15.0.4, which requires Angular version 14.0.0 or newer to work correctly.
Consider upgrading your application to use a more recent version of Angular.
  64 | }
  65 | SuiSidebarComponent.ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "15.0.4", ngImport: i0, type: SuiSidebarComponent, deps: [{ token: SuiSidebarService }], target: i0.ɵɵFactoryTarget.Component });
> 66 | SuiSidebarComponent.ɵcmp = i0.ɵɵngDeclareComponent({ minVersion: "14.0.0", version: "15.0.4", type: SuiSidebarComponent, selector: "sui-sidebar, [sui-sidebar]", inputs: { suiSidebarPosition: "suiSidebarPosition", suiSidebarWidth: "suiSidebarWidth", suiSidebarAnimation: "suiSidebarAnimation", suiInverted: "suiInverted", visible: "visible" }, outputs: { visibleChange: "visibleChange" }, host: { properties: { "class": "this.classes" } }, ngImport: i0, template: `
     |                            ^
  67 |     <ng-content></ng-content>
  68 |   `, isInline: true, encapsulation: i0.ViewEncapsulation.None });
  69 | __decorate(['
    at run (/Usersxxxnode_modules/@babel/core/lib/transformation/index.js:27:15)
    at run.next (<anonymous>)
    at transform (/Usersxxxnode_modules/@babel/core/lib/transform.js:22:33)
    at transform.next (<anonymous>)
    at step (/Usersxxxnode_modules/gensync/index.js:261:32)
    at /Usersxxxnode_modules/gensync/index.js:273:13
    at async.call.result.err.err (/Usersxxxnode_modules/gensync/index.js:223:11)
    at /Usersxxxnode_modules/gensync/index.js:37:40

./node_modules/ngx-semantic/fesm2015/ngx-semantic.mjs - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
TypeError: Cannot create property 'message' on string '/Usersxxxnode_modules/ngx-semantic/fesm2015/ngx-semantic.mjs: This application depends upon a library published using Angular version 15.0.4, which requires Angular version 14.0.0 or newer to work correctly.
Consider upgrading your application to use a more recent version of Angular.
  45 | }
  46 | NgxSemanticModule.ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "15.0.4", ngImport: i0, type: NgxSemanticModule, deps: [], target:m i0.ɵɵFactoryTarget.NgModule });
> 47 | NgxSemanticModule.ɵmod = i0.ɵɵngDeclareNgModule({ minVersion: "14.0.0", version: "15.0.4", ngImport: i0, type: NgxSemanticModule, exports: [SuiTabsModule,
     |                          ^
  48 |         SuiFlagModule,
  49 |         SuiIconModule,
  50 |         SuiListModule,'
    at run (/Usersxxxnode_modules/@babel/core/lib/transformation/index.js:27:15)
    at run.next (<anonymous>)
    at transform (/Usersxxxnode_modules/@babel/core/lib/transform.js:22:33)
    at transform.next (<anonymous>)
    at step (/Usersxxxnode_modules/gensync/index.js:261:32)
    at /Usersxxxnode_modules/gensync/index.js:273:13
    at async.call.result.err.err (/Usersxxxnode_modules/gensync/index.js:223:11)
    at /Usersxxxnode_modules/gensync/index.js:37:40

Error: node_modules/ngx-semantic/collections/breadcrumb/breadcrumb-divider.directive.d.ts:7:18 - error TS2314: Generic type 'ɵɵDirectiveDeclaration' requires 6 type argument(s).

7     static ɵdir: i0.ɵɵDirectiveDeclaration<SuiBreadcrumbDividerDirective, "[suiBreadcrumbDivider]", ["suiBreadcrumbDivider"], { "suiIcon": "suiIcon"; }, {}, never, never, false, never>;
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-semantic/collections/breadcrumb/breadcrumb-section.directive.d.ts:7:18 - error TS2314: Generic type 'ɵɵDirectiveDeclaration' requires 6 type argument(s).

7     static ɵdir: i0.ɵɵDirectiveDeclaration<SuiBreadcrumbSectionDirective, "[suiBreadcrumbSection]", ["suiBreadcrumbSection"], { "suiActive": "suiActive"; }, {}, never, never, false, never>;
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-semantic/collections/breadcrumb/breadcrumb.directive.d.ts:7:18 - error TS2314: Generic type 'ɵɵDirectiveDeclaration' requires 6 type argument(s).

7     static ɵdir: i0.ɵɵDirectiveDeclaration<SuiBreadcrumbDirective, "[sui-breadcrumb]", ["suiBreadcrumb"], { "suiSize": "suiSize"; }, {}, never, never, false, never>;
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-semantic/collections/form/form-field.directive.d.ts:17:18 - error TS2314: Generic type 'ɵɵDirectiveDeclaration' requires 6 type argument(s).

17     static ɵdir: i0.ɵɵDirectiveDeclaration<SuiFormFieldDirective, "[suiFormField]", ["suiFormField"], { "suiWidth": "suiWidth"; "suiError": "suiError"; "suiInline": "suiInline"; "disabled": "disabled"; "suiRequired": "suiRequired"; }, {}, never, never, false, never>;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-semantic/collections/form/form-fields.directive.d.ts:16:18 - error TS2314: Generic type 'ɵɵDirectiveDeclaration' requires 6 type argument(s).

16     static ɵdir: i0.ɵɵDirectiveDeclaration<SuiFormFieldsDirective, "[suiFormFields]", ["suiFormFields"], { "suiWidth": "suiWidth"; "suiInline": "suiInline"; "suiGrouped": "suiGrouped"; "suiEqualWidth": "suiEqualWidth"; }, {}, never, never, false, never>;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-semantic/collections/form/form.directive.d.ts:18:18 - error TS2314: Generic type 'ɵɵDirectiveDeclaration' requires 6 type argument(s).

18     static ɵdir: i0.ɵɵDirectiveDeclaration<SuiFormDirective, "[sui-form]", ["suiForm"], { "suiState": "suiState"; "suiSize": "suiSize"; "suiLoading": "suiLoading"; "suiEqualWidth": "suiEqualWidth"; "suiInverted": "suiInverted"; }, {}, never, never, false, never>;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-semantic/collections/grid/grid-column.directive.d.ts:19:18 - error[90m TS2314: Generic type 'ɵɵDirectiveDeclaration' requires 6 type argument(s).

19     static ɵdir: i0.ɵɵDirectiveDeclaration<SuiGridColumnDirective, "[suiGridColumn]", ["suiGridColumn"], { "suiWidth": "suiWidth"; "suiFloated": "suiFloated"; "suiColour": "suiColour"; "suiAlignment": "suiAlignment"; "suiDeviceVisibility": "suiDeviceVisibility"; }, {}, never, never, false, never>;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-semantic/collections/grid/grid-row.directive.d.ts:18:18 - error TS2314: Generic type 'ɵɵDirectiveDeclaration' requires 6 type argument(s).

18     static ɵdir: i0.ɵɵDirectiveDeclaration<SuiGridRowDirective, "[suiGridRow]", ["suiGridRow"], { "suiWidth": "suiWidth"; "suiAlignment": "suiAlignment"; "suiDeviceVisibility": "suiDeviceVisibility"; "suiEqual": "suiEqual"; "suiCentered": "suiCentered"; }, {}, never, never, false, never>;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-semantic/collections/grid/grid.directive.d.ts:30:18 - error TS2314: Generic type 'ɵɵDirectiveDeclaration' requires 6 type argument(s).

30     static ɵdir: i0.ɵɵDirectiveDeclaration<SuiGridDirective, "[sui-grid]", ["suiGrid"], { "suiWidth": "suiWidth"; "suiAlignment": "suiAlignment"; "suiDivided": "suiDivided"; "suiCelled": "suiCelled"; "suiPadded": "suiPadded"; "suiReversed": "suiReversed"; "suiRelaxation": "suiRelaxation"; "suiEqual": "suiEqual"; "suiCentered": "suiCentered"; "suiContainer": "suiContainer"; "suiStackable": "suiStackable"; "suiDoubling": "suiDoubling"; }, {}, never, never, false, never>;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-semantic/collections/menu/menu-header.directive.d.ts:5:18 - error TS2314: Generic type 'ɵɵDirectiveDeclaration' requires 6 type argument(s).

5     static ɵdir: i0.ɵɵDirectiveDeclaration<SuiMenuHeaderDirective, "[suiMenuHeader]", ["suiMenuHeader"], {}, {}, never, never, false, never>;
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-semantic/collections/menu/menu-item.directive.d.ts:9:18 - error TS2314: Generic type 'ɵɵDirectiveDeclaration' requires 6 type argument(s).

9     static ɵdir: i0.ɵɵDirectiveDeclaration<SuiMenuItemDirective, "[suiMenuItem]", ["suiMenuItem"], { "suiLink": "suiLink"; "suiActive": "suiActive"; "suiBrowser": "suiBrowser"; "disabled": "disabled"; }, {}, never, never, false, never>;
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-semantic/collections/menu/menu.directive.d.ts:27:18 - error TS2314: Generic type 'ɵɵDirectiveDeclaration' requires 6 type argument(s).

27     static ɵdir: i0.ɵɵDirectiveDeclaration<SuiMenuDirective, "[sui-menu]", ["suiMenu"], { "suiWidth": "suiWidth"; "suiAttached": "suiAttached"; "suiFixed": "suiFixed"; "suiColour": "suiColour"; "suiIcon": "suiIcon"; "suiSize": "suiSize"; "suiText": "suiText"; "suiSecondary": "suiSecondary"; "suiPointing": "suiPointing"; "suiTabular": "suiTabular"; "suiVertical": "suiVertical"; "suiFluid": "suiFluid"; "suiRight": "suiRight"; "suiPagination": "suiPagination"; "suiCompact": "suiCompact"; "suiStackable": "suiStackable"; "suiInverted": "suiInverted"; "suiBorderless": "suiBorderless"; }, {}, never, never, false, never>;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-semantic/collections/menu/sub-menu.directive.d.ts:6:18 - error TS2314: Generic type 'ɵɵDirectiveDeclaration' requires 6 type argument(s).

6     static ɵdir: i0.ɵɵDirectiveDeclaration<SuiSubMenuDirective, "[suiSubMenu]", ["suiSubMenu"], { "suiRight": "suiRight"; }, {}, never, never, false, never>;
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-semantic/collections/message/message-content.directive.d.ts:5:18 - error TS2314: Generic type 'ɵɵDirectiveDeclaration' requires 6 type argument(s).

5     static ɵdir: i0.ɵɵDirectiveDeclaration<SuiMessageContentDirective, "[suiMessageContent]", ["suiMessageContent"], {}, {}, never, never, false, never>;
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-semantic/collections/message/message-header.directive.d.ts:5:18 - error TS2314: Generic type 'ɵɵDirectiveDeclaration' requires 6 type argument(s).

5     static ɵdir: i0.ɵɵDirectiveDeclaration<SuiMessageHeaderDirective, "[suiMessageHeader]", ["suiMessageHeader"], {}, {}, never, never, false, never>;
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-semantic/collections/message/message-list.directive.d.ts:5:18 - error TS2314: Generic type 'ɵɵDirectiveDeclaration' requires 6 type argument(s).

5     static ɵdir: i0.ɵɵDirectiveDeclaration<SuiMessageListDirective, "[suiMessageList]", ["suiMessageList"], {}, {}, never, never, false, never>;
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-semantic/collections/message/message.component.d.ts:22:18 - error TS2314: Generic type 'ɵɵComponentDeclaration' requires 7 type argument(s).

22     static ɵcmp: i0.ɵɵComponentDeclaration<SuiMessageComponent, "[sui-message]", never, { "suiAttached": "suiAttached"; "suiState": "suiState"; "suiSize": "suiSize"; "suiColour": "suiColour"; "suiDismissible": "suiDismissible"; "suiIcon": "suiIcon"; "suiHidden": "suiHidden"; "suiVisible": "suiVisible"; "suiFloating": "suiFloating"; "suiCompact": "suiCompact"; }, {}, never, ["*"], false, never>;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-semantic/collections/table/table-data-cell.directive.d.ts:13:18 - error TS2314: Generic type 'ɵɵDirectiveDeclaration' requires 6 type argument(s).

13     static ɵdir: i0.ɵɵDirectiveDeclaration<SuiTableCellDirective, "[suiTableCell]", ["suiTableCell"], { "suiState": "suiState"; "suiTextAlignment": "suiTextAlignment"; "suiVerticalAlignment": "suiVerticalAlignment"; "suiActive": "suiActive"; "disabled": "disabled"; "suiCollapsing": "suiCollapsing"; "suiSelectable": "suiSelectable"; }, {}, never, never, false, never>;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-semantic/collections/table/table-header-cell.directive.d.ts:10:18 - 1merror TS2314: Generic type 'ɵɵDirectiveDeclaration' requires 6 type argument(s).

10     static ɵdir: i0.ɵɵDirectiveDeclaration<SuiTableHeaderCellDirective, "[suiTableHeaderCell]", ["suiTableHeaderCell"], { "suiTextAlignment": "suiTextAlignment"; "suiVerticalAlignment": "suiVerticalAlignment"; "suiWidth": "suiWidth"; }, {}, never, never, false, never>;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-semantic/collections/table/table-row.directive.d.ts:11:18 - error TS2314: Generic type 'ɵɵDirectiveDeclaration' requires 6 type argument(s).

11     static ɵdir: i0.ɵɵDirectiveDeclaration<SuiTableRowDirective, "[suiTableRow]", ["suiTableRow"], { "suiState": "suiState"; "suiTextAlignment": "suiTextAlignment"; "suiVerticalAlignment": "suiVerticalAlignment"; "suiActive": "suiActive"; "disabled": "disabled"; }, {}, never, never, false, never>;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-semantic/collections/table/table.directive.d.ts:26:18 - error TS2314: Generic type 'ɵɵDirectiveDeclaration' requires 6 type argument(s).

........
```
...and tons of more TS issues.

I'm trying to upgrade to angular 14 or 15 as the top of the error requests, but the documentation said it's supposed to work with any version from 9 on?

thank you in advance ! 🙏

**Comment by nikita-fuchs** [comment]
Update: The errors disappear after migrating to Angular 15. I guess it's ` "typescript": "^4.9.5",` that does the trick. 

The circumstance that I can't import selected modules though leads to collisions with components from the `ng2-semantic-ui` library :/ any way that I can, for example, import only the Tab functionality ? Thank you very much in advance.

**Comment by bolorundurowb** [comment]
@nikita-fuchs sorry for just responding. I haven't figured out a workaround for the naming conflict just yet. I'll keep looking into it. 
I am also working on getting the documentation up to date as all components have been developed meaning ideally you shouldnt need ng2-semantic-ui anymore

**Comment by nikita-fuchs** [comment]
Hey, in the meantime I've managed to upgrade the original ng2-semantic-UI to Angular up to version 16 (in an own fork, of course). I'm already using it in production. I didn't have the time to properly release it for every angular version for time reasons and beautifully maintain the readme, but here it is: https://www.npmjs.com/package/ngx-ng2-semantic-ui in the versions tab, you can find version 16 and a few others, no guarantee for the other versions though.
